# Generated by Django 3.0.8 on 2020-08-10 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_grade', models.IntegerField()),
                ('subject', models.CharField(choices=[('M', 'Maths'), ('S', 'Science'), ('E', 'English'), ('O', 'Overall')], max_length=1)),
                ('mid_term_marks', models.IntegerField()),
                ('final_term_marks', models.IntegerField()),
                ('final_grade', models.CharField(choices=[('A', 'Above 90%'), ('B', 'Above 80%'), ('C', 'Above 70%'), ('D', 'Above 60%'), ('E', 'Above 50%'), ('F', 'Below 50%')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('birthdate', models.DateField()),
                ('date_joined', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('M', 'Maths'), ('S', 'Science'), ('E', 'English')], max_length=1)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_class', models.IntegerField()),
                ('class_passed', models.BooleanField(default=False)),
                ('current_teachers', models.ManyToManyField(to='core.Teacher')),
                ('marksheets', models.ManyToManyField(to='core.Marksheet')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='marksheet',
            name='pupil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Student'),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Teacher'),
        ),
    ]
