# Generated by Django 3.0.8 on 2020-08-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('S', 'Student'), ('T', 'Teacher'), ('A', 'Admin')], default='S', max_length=1),
            preserve_default=False,
        ),
    ]
