# Generated by Django 3.0.8 on 2020-08-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='marksheets',
            field=models.ManyToManyField(blank=True, to='core.Marksheet'),
        ),
    ]
