# Generated by Django 3.0.8 on 2020-08-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200812_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_joined',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='final_grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'B'), ('D', 'C'), ('E', 'D'), ('F', 'F')], max_length=1),
        ),
    ]
