# Generated by Django 3.0.8 on 2020-08-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200812_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='marksheets',
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='final_grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1),
        ),
    ]
