# Generated by Django 3.0.8 on 2020-08-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200816_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_class',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
