# Generated by Django 3.0.8 on 2020-08-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200817_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_joined',
            field=models.IntegerField(blank=True, choices=[(1, 'Class 1'), (2, 'Class 2'), (3, 'Class 3'), (4, 'Class 4'), (5, 'Class 5'), (6, 'Class 6'), (7, 'Class 7'), (8, 'Class 8'), (9, 'Class 9'), (10, 'Class 10')], null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_class',
            field=models.IntegerField(blank=True, choices=[(1, 'Class 1'), (2, 'Class 2'), (3, 'Class 3'), (4, 'Class 4'), (5, 'Class 5'), (6, 'Class 6'), (7, 'Class 7'), (8, 'Class 8'), (9, 'Class 9'), (10, 'Class 10')], null=True),
        ),
    ]
