# Generated by Django 3.0.8 on 2020-08-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(to='core.Class'),
        ),
        migrations.AlterField(
            model_name='class',
            name='grade',
            field=models.CharField(blank=True, choices=[(1, 'Class 1'), (2, 'Class 2'), (3, 'Class 3'), (4, 'Class 4'), (5, 'Class 5'), (6, 'Class 6'), (7, 'Class 7'), (8, 'Class 8'), (9, 'Class 9'), (10, 'Class 10')], max_length=1, null=True),
        ),
    ]
