# Generated by Django 3.0.8 on 2020-08-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200819_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='session_finished',
            field=models.BooleanField(default=False),
        ),
    ]
