# Generated by Django 3.0.8 on 2020-08-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200822_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalgrades',
            options={'verbose_name_plural': 'Final Grades'},
        ),
        migrations.AddField(
            model_name='student',
            name='school_finished',
            field=models.BooleanField(default=False),
        ),
    ]
