# Generated by Django 3.0.8 on 2020-08-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200822_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='session_finished',
        ),
    ]
