name: pages-build-deployment


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install -g gatsby-cli
      - run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
      - run: echo -n 'nvm "$@" && echo $NVM_BIN >> $GITHUB_PATH' >>  ~/.nvm/nvm.sh
      - run: sudo cp ~/.nvm/nvm.sh /usr/local/bin/nvm
      - run: sudo chmod +x /usr/local/bin/nvm
      - run: nvm install
#       - run: sh install_nvm.sh
#       - run: sudo apt-get install npm
      - run: nvm install v16.15.1
      - run: yarn
      - run: npm start
      
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: npm run build
      - run: npm run serve
