name: pages-build-deployment


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#       - uses: actions/jekyll-build-pages@v1.0.5
#       - uses: actions/deploy-pages@v1.0.8
      - run: sh install_nvm.sh
      - run: nvm install
      - run: npm install -g gatsby-cli
      - run: yarn
      - run: npm start
      
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: npm run build
      - run: npm run serve
